# Generated by Django 6.1 on 2026-08-16 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='created', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('started', 'Started'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='draft', max_length=20)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('target_medium', models.PositiveIntegerField(blank=True, null=True)),
                ('target_hard', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('leetcode_url', models.URLField(blank=True)),
                ('difficulty', models.CharField(choices=[('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('primary_pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_problems', to='tracker.pattern')),
                ('secondary_patterns', models.ManyToManyField(blank=True, related_name='secondary_problems', to='tracker.pattern')),
            ],
            options={
                'ordering': ['leetcode_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProblemAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('pseudocode', 'Pseudocode'), ('test_design', 'Test Design'), ('implementation', 'Implementation'), ('debugging', 'Hidden-Case Debugging'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('phase_started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_from_status', models.CharField(blank=True, max_length=20)),
                ('reading_seconds', models.PositiveIntegerField(default=0)),
                ('pseudocode_seconds', models.PositiveIntegerField(default=0)),
                ('test_design_seconds', models.PositiveIntegerField(default=0)),
                ('implementation_seconds', models.PositiveIntegerField(default=0)),
                ('debugging_seconds', models.PositiveIntegerField(default=0)),
                ('novelty', models.CharField(choices=[('never_seen', 'Never Seen'), ('seen_but_never_solved', 'Seen But Never Solved'), ('solved_long_ago', 'Solved Long Ago'), ('recently_solved', 'Recently Solved'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('pattern_identification_result', models.CharField(blank=True, choices=[('correct', 'Correct'), ('partial', 'Partial'), ('incorrect', 'Incorrect'), ('not_identified', 'Not Identified')], max_length=20)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('first_pass_accepted', models.BooleanField(default=False)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - No idea how I would reproduce this'), (2, '2 - Weak understanding'), (3, '3 - Understand solution'), (4, '4 - Could probably reconstruct it'), (5, '5 - Could confidently reconstruct it later')], null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('predicted_primary_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_primary_attempts', to='tracker.pattern')),
                ('predicted_secondary_patterns', models.ManyToManyField(blank=True, related_name='predicted_secondary_attempts', to='tracker.pattern')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='tracker.problem')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tracker.test')),
            ],
            options={
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('minimum_input', 'Minimum Input'), ('maximum_input', 'Maximum Input'), ('boundary', 'Boundary'), ('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('duplicates', 'Duplicates'), ('all_equal', 'All Equal'), ('alternating', 'Alternating'), ('negative_values', 'Negative Values'), ('overflow', 'Overflow'), ('off_by_one', 'Off-by-One'), ('adversarial', 'Adversarial'), ('custom', 'Custom')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('expected_behavior', models.CharField(blank=True, max_length=500)),
                ('did_find_bug', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('problem_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='tracker.problemattempt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROBLEM_STARTED', 'Problem Started'), ('PROBLEM_UNDERSTOOD', 'Problem Understood'), ('PATTERN_IDENTIFIED', 'Pattern Identified'), ('PSEUDOCODE_STARTED', 'Pseudocode Started'), ('TEST_DESIGN_STARTED', 'Test Design Started'), ('IMPLEMENTATION_STARTED', 'Implementation Started'), ('SUBMITTED', 'Submitted'), ('SUBMISSION_FAILED', 'Submission Failed'), ('DEBUGGING_STARTED', 'Debugging Started'), ('ACCEPTED', 'Accepted'), ('ABANDONED', 'Abandoned'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed')], max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('problem_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.problemattempt')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_number', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('wrong_answer', 'Wrong Answer'), ('tle', 'TLE'), ('mle', 'MLE'), ('runtime_error', 'Runtime Error'), ('other', 'Other')], max_length=20)),
                ('failure_type', models.CharField(blank=True, choices=[('wrong_algorithm', 'Wrong Algorithm'), ('incorrect_pattern', 'Incorrect Pattern'), ('logic_error', 'Logic Error'), ('implementation_error', 'Implementation Error'), ('edge_case', 'Edge Case'), ('off_by_one', 'Off-by-One'), ('complexity_tle', 'Complexity / TLE'), ('memory_limit', 'Memory Limit'), ('misread_problem', 'Misread Problem'), ('incorrect_data_structure', 'Incorrect Data Structure'), ('language_syntax', 'Language / Syntax'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='tracker.problemattempt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='test_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='tracker.testplan'),
        ),
        migrations.CreateModel(
            name='TestPlanProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('novelty', models.CharField(choices=[('never_seen', 'Never Seen'), ('seen_but_never_solved', 'Seen But Never Solved'), ('solved_long_ago', 'Solved Long Ago'), ('recently_solved', 'Recently Solved'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('selection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('expected_primary_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_primary_plan_problems', to='tracker.pattern')),
                ('expected_secondary_patterns', models.ManyToManyField(blank=True, related_name='expected_secondary_plan_problems', to='tracker.pattern')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_appearances', to='tracker.problem')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_problems', to='tracker.testplan')),
            ],
            options={
                'ordering': ['test_plan', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedFailureMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('test_plan_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_failure_modes', to='tracker.testplanproblem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='problemattempt',
            constraint=models.UniqueConstraint(fields=('test', 'problem'), name='unique_problem_per_test'),
        ),
        migrations.AddConstraint(
            model_name='testplanproblem',
            constraint=models.UniqueConstraint(fields=('test_plan', 'problem'), name='unique_problem_per_plan'),
        ),
    ]
